#!/usr/bin/env python3


import subprocess
import sys

range = 20

output = subprocess.run(
    ["pactl", "list", "sink-inputs"], stdout=subprocess.PIPE
).stdout.decode()
output = output.split("\n")
word = 'media.name = "Spotify"'

for i, line in enumerate(output):
    if word in line:
        end = i
        start = i - range
        if start < 0:
            start = 0
for element in output[start:end]:
    if "Sink Input #" in element:
        output = element.strip("Sink Input #")

argc = len(sys.argv)
if argc == 1:
    print(":) :?")
    quit()
elif argc != 2:
    print("Error: expected one argument")
    quit()

arg = sys.argv[1]
if arg == "-i":
    subprocess.run(
        ["pactl", "set-sink-input-volume", output, "+5%"], stdout=subprocess.PIPE
    ).stdout.decode()
elif arg == "-d":
    subprocess.run(
        ["pactl", "set-sink-input-volume", output, "-5%"], stdout=subprocess.PIPE
    ).stdout.decode()
else:
    print("Error: invalid argument")
